name: Check the source code
on: [pull_request]
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - name: npm のインストール
        run: npm ci --no-audit --progress=false --silent
      - name: astro
        run: npm run check:astro
      - name: prettier
        run: npm run check:prettier
      - name: stylelint
        run: npm run check:stylelint
      - name: eslint
        run: npm run check:eslint
      - name: vitest
        run: npm run check:vitest
      - name: build
        run: npm run build
      - name: HTML5Validator
        uses: Cyb3r-Jak3/html5validator-action
        with:
          root: dist/
