name: Check the source code
on: [pull_request]
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - name: npm のインストール
        run: npm ci --no-audit --progress=false --silent
      - name: astro
        run: npm run astro-c
      - name: prettier
        run: npm run prettier-c
      - name: stylelint
        run: npm run stylelint-c
      - name: eslint
        run: npm run eslint-c
      - name: vitest
        run: npm run vitest-c
