name: release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - name: npm のインストール
        run: npm ci --no-audit --progress=false --silent
      - name: 静的ファイルの作成
        run: npm run build
      - name: distフォルダのzipファイル作成
        run: zip dist.zip -r dist
      - name: Releaseノートの作成
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: dist.zip
