name: release
# on:
#   push:
#     tags:
#       - '*'
on: push
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: 前のタグにチェックアウト
        id: checkout-previous
        run: |
          git fetch --tags --force
          previous_tag=$(git tag --sort=v:refname | tail -n 2 | head -n 1)
          echo $previous_tag
          git checkout $previous_tag

      - name: npm のインストール
        run: npm ci --no-audit --progress=false --silent

      - name: 前のタグでビルド
        run: npm run build

      - name: 前のタグのビルド成果物を保存
        run: mv dist dist_previous

      - name: 最新のタグにチェックアウト
        id: checkout-latest
        run: |
          latest_tag=$(git tag --sort=v:refname | tail -n 1)
          echo $latest_tag
          git checkout $latest_tag

      - name: npm のインストール
        run: npm ci --no-audit --progress=false --silent

      - name: 最新のタグでビルド
        run: npm run build

      - name: ビルド成果物の差分を取得
        id: diff
        run: diff -r dist_previous dist || true

      # - name: Releaseノートの作成
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     generate_release_notes: true
      #     body: ${{ steps.diff.outputs.result }}
